### ISSUE TITLE
Request to sync packages

### ISSUE THREAD

**Issue by erikdubois** [xlanor/mirror.jingk.ai#12]
I was just wondering if you could share packages and isos of ArcoLinux.

https://arcolinux.info/.

We are a learning distro. We teach people Linux then Arch Linux and then ArcoLinux.

In order to get updates in we would like to spread our packages over the globe.

You can find our packages on the Belgium ftp server.

https://ftp.belnet.be/arcolinux/

Would it be possible to mirror these to your server?

Kind regards
Erik Dubois

**Comment by xlanor** [comment]
Hi Erik (@erikdubois),

Do you have a rsync server setup? that would be more convenient with my scripts.

Please do note that mirror.jingk.ai will be unavaliable for a week or so as I am currently in the midst of relocating to London. The physical servers will still be in Singapore for the forseeable future.

Regards,

Jingkai.

**Comment by xlanor** [comment]
cc-ing @narapon, admin of mirror.kst.asia to also serve as a fallover.

**Comment by xlanor** [comment]
mirror.funami.tech has rsync up, I will sync off it. Currently on the way.

**Comment by erikdubois** [comment]
indeed you can use that one too

cheers
Erik

Op di 15 mrt. 2022 om 16:40 schreef jingkai. ***@***.***>:

**Comment by xlanor** [comment]
Cool, currently running initial sync. Will set up cron scripts when ready.

Jingkai

**Comment by xlanor** [comment]
Ready to serve packages/isos @erikdubois

**Comment by erikdubois** [comment]
3 questions

1. what is the server you use now to sync from
2. how many times a day do you sync
3. http://mirror.kst.asia - This one will come later I guess - was a fall-back - should I do something with it?

**Comment by xlanor** [comment]
Hi Erik,

1) syncing off funami.tech currently.
2) 00, 12, twice a day
3) Talking to the admin to see if he is willing to host, will inform you seperately

**Comment by erikdubois** [comment]
Do check your server?

I guess we are not syncing anymore.

Cheers

Erik

Op di 15 mrt 2022 om 16:33 schreef jingkai. ***@***.***>:

**Comment by erikdubois** [comment]
is your mail still being used?

I see no changes in the syncing of ArcoLinux mirror

https://mirror.jingk.ai/arcolinux/iso/

cheers
erik

Op za 2 dec 2023 om 09:22 schreef Erik Dubois ***@***.***>:

**Comment by xlanor** [comment]
Currently on vacation.

Checked other syncs based on lastsync and they appear to be fine . Not sure what's up with arco: will check again

**Comment by xlanor** [comment]
I do not have a laptop so will not be able to investigate till 2 Jan GMT

**Comment by erikdubois** [comment]
all good
take your time

Op zo 31 dec 2023 om 05:59 schreef jingkai. ***@***.***>:

**Comment by erikdubois** [comment]
Morning

I am considering removing the mirror from our list

[image: image.png]
Did you check your servers recently?

This will not do

Cheers
ERik

Op wo 16 mrt 2022 om 11:00 schreef jingkai. ***@***.***>:

**Comment by xlanor** [comment]
Please remove.

Arco is the only mirror I am constantly having sync issues with as my other syncs like arch/endeavour appear to be fine.

Honestly, I would prefer to not have that headache.

**Comment by erikdubois** [comment]
ok


Op wo 6 mrt 2024 om 09:16 schreef jingkai. ***@***.***>:

> Please remove.
>
> Sent from my iPhone
>
>
